version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: mariguapo
      DB_PASSWORD: 123456789
      DB_NAME: examenservidores

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: examenservidores 
      MYSQL_USER: mariguapo
      MYSQL_PASSWORD: 123456789
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: